name = "ogp-image-generator"
main = "src/index.tsx"
compatibility_date = "2024-11-24"
compatibility_flags = [ "nodejs_compat" ]

assets = { directory = "./public/", binding = "ASSETS" }

[observability]
enabled = true
head_sampling_rate = 1